---
- name: test if dovecot_mailbox_location is set correctly
  assert:
    that:
      - dovecot_mailbox_location is defined
    quiet: yes

- name: test if dovecot_mail_access_groups is set correctly
  assert:
    that:
      - dovecot_mail_access_groups is defined
    quiet: yes
