---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if ports are open
      ansible.builtin.wait_for:
        port: "{{ item }}"
        timeout: 2
      loop:
        - "110"
        - "143"
        - "993"
        - "995"
